### PR TITLE
Add personal api key support

### PR DESCRIPTION
**Pull request by MhhhxX**
I implemented support for personal api keys from fanarttv. You can set the key in a new category in the settings.
With the additional key the script receives more current data from fanart.tv.

useful links:
http://docs.fanarttv.apiary.io/#introduction/api_key-and-client_key
https://fanart.tv/get-an-api-key/
https://fanart.tv/2015/01/personal-api-keys/

### CODE REVIEW

**Comment by stefansielaff** [comment]
Thanks!
Currently I'm heavily changing the code in the cleanup branch, which directly affects the settings. If you find the time you could make your code compatible, I'll adopt it otherwise.
If possible I would prefer naming the variable like the parameter "client_key" to create a more consistent realation what do you think?

**Comment by MhhhxX** [comment]
I already forked your cleanup branch and adopted the code ;) I'll make a pull request.
Yes you're right I'll change the parameter name to "client_key".

**Comment by stefansielaff** [comment]
Awesome :)
One last thing, I'm not sure how fanart.tv will respond if client_key is empty - did you test that? Otherwise we should only append the parameter to the url if it's filled (and maybe has a sane length).

**Comment by MhhhxX** [comment]
Yes I tested it. The api responses even if the client_key= term is empty
look at this link:
http://webservice.fanart.tv/v3/music/66c662b6-6e2f-4930-8610-912e24c63ed1?api_key=65169f993d552483391ca10c1ae7fb03&client_key=

Same response as without the client_key term:
http://webservice.fanart.tv/v3/music/66c662b6-6e2f-4930-8610-912e24c63ed1?api_key=65169f993d552483391ca10c1ae7fb03

**Comment by stefansielaff** [comment]
Merged the "cleanup" version, closing this one - thanks!

**Pull request closed without merging**
